### ISSUE TITLE
can't log in wallet 

### ISSUE THREAD

**Issue by WestlE** [hivewallet/hivewallet.com#40]
I Сan't log in the wallet, registered new - all perfectly, but the wallet balance is ~40$ can't go.
Writes sync for about 40 minutes, placema since yesterday, when I got the money in the wallet.
What data I can provide to you to restore the access?

**Comment by w-hive** [comment]
Hi Vlad,

Try our staging site with your passphrase? http://hive-js.herokuapp.com

**Comment by WestlE** [comment]
What? http://prntscr.com/8o2y2u

**Comment by w-hive** [comment]
Apologies but I can't read Russian and don't really understand what you are asking me here.

By the way please be aware of two things:

1) We cannot control anything about the balances of the wallet. We don't _know_ about your balances or transactions at all.

2) I'll try to help you, but Hive is not officially supported anymore. https://twitter.com/hivewallet/status/645402186260721664

**Comment by WestlE** [comment]
I can't make payments even on the most minimal amount, though the money in the account there are

**Comment by w-hive** [comment]
You tried using the staging version right? https://hive-js.herokuapp.com ?

**Comment by WestlE** [comment]
through it and tried

**Comment by WestlE** [comment]
If payment of any amount - I don't have enough money. 
When I login official site - eternal download.
Can send me the money manually to my second wallet?

**Comment by w-hive** [comment]
You probably need to sweep your keys into another wallet then; I'm not able to help you much with this myself. If you have iOS, I can recommend Bread Wallet. It takes the passphrase directly.

And no, we cannot send any of your tokens anywhere. We have _zero control over wallet balances_. Hive is not a Bitcoin bank.

**Comment by WestlE** [comment]
Can you try for me to transfer money to another account?

**Comment by WestlE** [comment]
I will provide data from the account

**Comment by WestlE** [comment]
Why doesn't it work the main site with MY purse?

**Comment by WestlE** [comment]
And how to download bitcoin key?

**Comment by w-hive** [comment]
Have no idea why it's not working sadly.

Your passphrase *IS* your private key. You can use the tools at bip32.org to convert it.

**Comment by w-hive** [comment]
Closing this, but we can continue talking here.

**Comment by WestlE** [comment]
why you ignore me?

**Comment by w-hive** [comment]
Not ignoring you, I answered as best I can. Look above.

**Comment by WestlE** [comment]
May be you have lesson, woh to use this key.

**Comment by w-hive** [comment]
I don't, unfortunately. It's something I've been meaning to put together (a BIP32 export tutorial).

The best thing I can recommend right now is to find an iOS device, and put your passphrase into Bread Wallet on that platform, and send your funds where you need them to go.

**Comment by WestlE** [comment]
I use coinkite.com to acces to my wallet, but when i config it a have new bitcoind adress and 0 at balance.
wtf?

**Comment by w-hive** [comment]
Ask them what their BIP32 derivation path is. Maybe it isn't compatible with Hive's. I've never tried it.
