### ISSUE TITLE
Closed Site

### ISSUE THREAD

**Issue by rogueops** [hivewallet/hivewallet.com#43]
You closed your site and I did not know so you took my coins with you.

**Comment by mackuba** [comment]
Hive does not have and never had your coins, it's not built this way. The coins are always accessible through the 12-word passphrase, you only need to find a tool with which to access them. For example, on iOS the Breadwallet app can be used to restore your Hive Web wallet from the 12 words.

**Comment by ghost** [comment]
No, and we never had them in the first place. Hive was a BIP32/BIP39
wallet. Enter your passphrase (effectively your private key) into
another wallet following a similar standard, and you will have access
again. If you use the iOS platform, we recommend Bread Wallet. For
Mycelium instructions, see Jan's Tweet at twitter.com/hivewallet

**Comment by rogueops** [comment]
@w-hive yes I got that from the post above yours

**Comment by rogueops** [comment]
@mackuba Will you be posting your web wallet code? If not I would like to talk to you about purchasing your web wallet code.

**Comment by ghost** [comment]
It has always been available. See http://github.com/hivewallet for all
of our code.

**Comment by rogueops** [comment]
i cant seem to find the right one, what is it called?

**Comment by gh0stshell** [comment]
i am guessing it is the hive-js one

I get these errors when running npm install

npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.3 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by ghost** [comment]
These projects have not been maintained for more than a year and a half.
Sorry, but we really cannot offer any support. We wish you luck however.

**Comment by rogueops** [comment]
Thanks after a little google-fu I was able to get it, I did do the correct repo?

**Comment by rogueops** [comment]
your site was great and I would like to get it back online and build on it since it was my favorite by far, much appreciation for your work and for bringing it to the web

**Comment by rogueops** [comment]
anyway I can purchase your domain from you?

**Comment by ghost** [comment]
If you're serious about resuming the service, please email me at
w@hivewallet.com and tell me about your team, funding, etc.

**Comment by rogueops** [comment]
sent, you can close and we can email from this point on
